### ISSUE TITLE
MORE message not working properly with 1 row windows

### ISSUE THREAD

**Issue by rockersuke** [nataliapc/msx2daad#12]
Every time I update the text in a 1 row window (for example, a status bar) the "more" message will appear at the wrong time, pausing the whole game till a key is pressed.
Actually, this also happens in the original DAAD terps if you update the status bar content with an ordinary MESSAGE condact, but can be avoided if you use MES instead (which i Usually do).
This does not happen in msx2daad, where MES also invokes the "more".
So perhaps in the original MESSAGE and MES work in a different way concerning the "more" count.

**Comment by rockersuke** [comment]
Ojo, que no descarto que el problema venga de que en msx2daad MESSAGE y MES no se diferencien uno de otro y no tenga nada que ver con el "more"

**Comment by nataliapc** [comment]
Mmmm it's strange what you say, since I was precisely adjusting it.

I use "MODE 2" to disable "more" feature in 1 row windows.
Maybe the problem is the initial state of MODE values in msx2daad?

You can check it here using IMGOFF:
[https://nataliapc.itch.io/zakilwoodmsx2](https://nataliapc.itch.io/zakilwoodmsx2)

**EDIT:**
Tested with classic DAAD interpreter (MSX): "more" don't appears in 1 row windows.
Fixed!
